### ISSUE TITLE
TP-LINK AC 600 Archer T2UH seems to be not supported

### ISSUE THREAD

**Issue by thomasdoerr** [volumio/Build#291] opened 2018-01-18 10:04 UTC
Hi, I commented in this post https://github.com/volumio/Volumio2/issues/1452 that my volumio installation (after the update from 2.246 to the latest 2.348) freezes, if my TP-LINK AC 600 Archer T2UH was plugged in. In the moment when I plug it in, volumio freezes when I try to fire a command. I noticed that, since nothing worked after the update.

xipmix asked me to open an issue here. 

My pi is now running without the TP-LINK. One of the main raisons why I used the TP-LINK was, that channel 12/13 were not enabled on the pi and my router sometimes used these channels. 
Today, probably after installing "http://www.fars-robotics.net/install-wifi -O /usr/bin/install-wifi", both channels are active. So everything is fine for me now, but there might be others having the same problem.
Regards, Thomas

**Comment by macmpi** [comment] 2018-01-18 10:46
Strange...Volumio build is indeed supposed to install MrEngman drivers...

Can you give output of `lsmod `and `lsusb` when you have the dongle plugged and working?
Can you show `dmesg` output when you plug the dongle on working / non-working setup?

**Comment by thomasdoerr** [comment] 2018-01-18 10:53
hmm, as I wrote, when I plug in the dongle, I'm unable to fire any command. I fixed my machine, so I need to recreate the situation. I'll try to reproduce it. Give me a little bit of time :-)

**Comment by macmpi** [comment] 2018-01-18 10:56
if you can already provide info on working setup, that good.
Apparently that beast uses mt7610 and Volumio script pulls the right driver file (that exists)

**Comment by thomasdoerr** [comment] 2018-01-18 10:58
ok

**Comment by macmpi** [comment] 2018-01-18 11:16
In the meantime, I checked v2.348 image file, and can confirm all drivers and firmware files are where they should (in particular for mt7610).

Could you check if your USB dongle works with a newly imaged v2.348 SD please?
Maybe something went wrong in the upgrade due to previous file modifications in original install...

**Comment by thomasdoerr** [comment] 2018-01-18 11:51
I checked it with a fresh image, this is always my first check, if I have update problems. Same issue.
But now I managed to access volumio via ssh in both cases with plug dongle.
You'll find two text files with (hopefully) the information you asked. In the screenshot you see, that in the case of 2.348 plus TP-LINK, when I try to call sudo journalctl -f it hangs.

Hope you'll be able to find the bug! :-)


[tp-link-issue.zip](https://github.com/volumio/Build/files/1642688/tp-link-issue.zip)

**Comment by macmpi** [comment] 2018-01-18 16:13
> But now I managed to access volumio via ssh in both cases with plug dongle.

Which cases precisely (base image, upgraded, + drivers manual install )?
In provided logs, we see driver error in both working & not working cases!...

> One of the main raisons why I used the TP-LINK was, that channel 12/13 were not enabled on the pi and my router sometimes used these channels.

Not sure I understand this initial comment either BTW: you wanted to use 5Ghz band (requiring USB dongle) just because 2.4GHz channel 12/13 did not work?
To allow Volumio wifi on those channels (whatever wifi interface, built-in or USB), you need to set your region in CRDA, as [per this](https://volumio.org/forum/configure-volumio-wifi-without-using-cabled-ethernet-t3953-20.html#p34879).
Maybe this driver does not like it not being set...

**Comment by thomasdoerr** [comment] 2018-01-18 18:20
I did a fresh install of version 2.246, TP-LINK was plugged in, everthing worked 
-> 2246-with-tp-link-working.txt 

I updated that instance to 2.348, TP-LINK was still plugged, I had no connection via volumio.local, but was able to connect via ssh 
-> 2348-with-tp-link-not-working.txt

And yes, I also noticed the error in both case. When I read your last comment, I asked myself, which WIFI adapter was working when I installed 2.246. Perhaps the built-in adapter did the work and the TP-LINK was there, but didn't cause a problem for the whole system, but didn't work either. Im not sure.

Thanks for the tip "setting the region in CRDA". I didn't know that and as far as I remember, a few months ago I found a post where someone wrote, that rasberry pi doesn't support that at all.

**Comment by volumio** [comment] 2018-01-18 18:48
My 2 cents:
AC dongles are quite power hungry. On the last volumio version we enabled performance CPU governor. My assumption is that in this configuration, the pi does not get enough power and it becomes unstable.
You can see if changing the governor to ondemand solves this.

To do so:
nano /etc/default/cpufrequtils

change to ondemand. Reboot

let me know

**Comment by macmpi** [comment] 2018-01-19 10:08
@thomasdoerr you can check which wifi HW is being actively used as wlan0 with `iwconfig` command.
Also, for sake of clarity, you may temporarily desactivate Pi3 onboard wifi by adding `dtoverlay=pi3-disable-wifi` statement in `/boot/config.txt`

As for CRDA support on Pi, yes [it is confirmed working](https://volumio.org/forum/configure-volumio-wifi-without-using-cabled-ethernet-t3953-30.html#p40285).

Please check @volumio suggestion, as power limitation may very well be the cause...

**Comment by thomasdoerr** [comment] 2018-01-20 10:25
Hi,
I tried to change the governor to ondemand and also disabled the wifi.
Nothing helped.

Since I don't need the TP-LINK AC 600 Archer T2UH anymore, because everything works with the build-in wifi, I'd like to close this issue now if this is fine for you.

**Comment by macmpi** [comment] 2018-01-20 12:40
Did you fixed built-in wifi operations with CRDA then?

Really strange for TP-LINK: would be helpful to understand what causes this regression though, as similar issue may impact some other users...

You say that drivers installed with `install-wifi` script seem to work: is that the same if you do it on top of stock 2.348?
Maybe MD5 checksuming drivers & firmware files from http://www.fars-robotics.net/mt7610-4.9.65-v7-1056.tar.gz and comparing with those of stock 2.348 would help check MrEngman files may not have been changed between 2.348 build date and those currently available with `install-wifi`...

Any chance you could have 2 SD handy for a little while, one with genuine 2.246 and one with genuine 2.348 to help investigate further?
(or even test several releases in between 2.344 2.323 **2.310** 2.309 2.296 2.295 2.285, to see when the problem got introduced; previous images at: http://updates.volumio.org/pi/volumio/2.xxx/volumio-2.xxx-2017-xx-xx-pi.img.zip, see x values [here](https://volumio.org/forum/changelog-t1575.html))

There have been some dwc_otg config related changes in `/boot/cmdline.txt` [recently](https://github.com/volumio/Build/commits/master/scripts/raspberryconfig.sh): @volumio what do you think?

**Comment by thomasdoerr** [comment] 2018-01-20 14:28
> Did you fixed built-in wifi operations with CRDA then?

Yes :-)

Okay, I'll investigate further. I can't guarantee a reponse time like in the last days, but I'll come back to you as soon as possible!

**Comment by macmpi** [comment] 2018-01-20 16:52
Ok, so checksummed driver files and...they are different!... (firmware files are same).
So it's likely MrEngman rebuilt & re-issued that driver after v2.348 was built with a bad one...
Just bad luck.
Hopefully this will not happen in next release.

You may close this issue, and re-open if the issue re-appears with next **brand-new image** (mind that if you just update the image in which you used `install-wifi` script, it will mostly likely then have an unmatching driver...): now you only have 1 test to do then at next release  ;)

note to @volumio : would be nice to get [UI for setting CRDA & other regional stuff](https://github.com/volumio/Volumio2-UI/issues/317)

**Comment by thomasdoerr** [comment] 2018-01-20 17:19
ok good news.
I was just playing around, removed my hifiberry and started checking version 2.310. 
But I'll stop that now. Feel free to contact me, if you need someone to test the new version!

**Closed** 2018-01-20 17:25 UTC

**Comment by macmpi** [comment] 2018-02-11 07:32
@thomasdoerr 
now [2.361](https://volumio.org/get-started/) is out, you may want to check/confirm if your dongle is supported out of a re-imaged SD.

**Comment by thomasdoerr** [comment] 2018-02-11 16:07
still the same, my pi freezes in the moment I plug the TP-LINK in :-(
I installed a fresh image (2.361), enabled SSH and plugged a LAN cable in order to be able to access volumio without wifi when wifi crashes. Here is the output when I plugged TP-LINK in: 

                      /\_ \                        __
         __  __    ___\//\ \    __  __    ___ ___ /\_\    ___
        /\ \/\ \  / __`\\ \ \  /\ \/\ \ /' __` __`\/\ \  / __`\
        \ \ \_/ |/\ \L\ \\_\ \_\ \ \_\ \/\ \/\ \/\ \ \ \/\ \L\ \
         \ \___/ \ \____//\____\\ \____/\ \_\ \_\ \_\ \_\ \____/
          \/__/   \/___/ \/____/ \/___/  \/_/\/_/\/_/\/_/\/___/

             Free Audiophile Linux Music Player - Version 2.0

          C 2015 Michelangelo Guarise - Volumio Team - Volumio.org


Volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
volumio@Volumio:~$ sudo journalctl -f
-- Logs begin at Sat 2018-02-10 16:19:46 UTC. --
Feb 11 15:57:20 Volumio sshd[9088]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Feb 11 15:57:52 Volumio sshd[9333]: Accepted password for volumio from 192.168.178.36 port 58343 ssh2
Feb 11 15:57:52 Volumio sshd[9333]: pam_unix(sshd:session): session opened for user volumio by (uid=0)
Feb 11 15:57:52 Volumio systemd[1]: Starting Session c2 of user volumio.
Feb 11 15:57:52 Volumio systemd[1]: Started Session c2 of user volumio.
Feb 11 15:57:52 Volumio systemd-logind[724]: New session c2 of user volumio.
Feb 11 15:57:52 Volumio sshd[9333]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Feb 11 15:57:52 Volumio sshd[9333]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Feb 11 15:58:01 Volumio sudo[9438]: volumio : TTY=pts/1 ; PWD=/home/volumio ; USER=root ; COMMAND=/bin/journalctl -f
Feb 11 15:58:01 Volumio sudo[9438]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: new high-speed USB device number 6 using dwc_otg
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: New USB device found, idVendor=148f, idProduct=761a
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: Product: WiFi
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: Manufacturer: MediaTek
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: SerialNumber: 1.0
Feb 11 15:58:41 Volumio kernel: mt7610u: loading out-of-tree module taints kernel.
Feb 11 15:58:41 Volumio wpa_supplicant[8172]: rfkill: event: idx=1 type=1 op=0 soft=0 hard=0
Feb 11 15:58:41 Volumio kernel:

                                === pAd = c0faa000, size = 856120 ===
Feb 11 15:58:41 Volumio kernel: <-- RTMPAllocTxRxRingMemory, Status=0
Feb 11 15:58:41 Volumio kernel: <-- RTMPAllocAdapterBlock, Status=0
Feb 11 15:58:41 Volumio kernel: ==>mt7610u_chip_onoff(): OnOff:1, Reset= 0, pAd->WlanFunCtrl:0x0, Reg-WlanFunCtrl=0xff000002
Feb 11 15:58:41 Volumio kernel: MACVersion = 0x76502000
Feb 11 15:58:41 Volumio kernel: MACVersion = 0x76502000
Feb 11 15:58:41 Volumio kernel: 80211> RFICType = 3
Feb 11 15:58:41 Volumio kernel: 80211> Number of channel = 44
Feb 11 15:58:41 Volumio kernel: 80211> Number of rate = 12
Feb 11 15:58:41 Volumio kernel: 80211> CurTxPower = 0 dBm
Feb 11 15:58:41 Volumio kernel: 80211> TxStream = 0
Feb 11 15:58:41 Volumio kernel: crda> requlation requestion by country IE:
Feb 11 15:58:41 Volumio kernel: DE
Feb 11 15:58:41 Volumio kernel: 80211> CFG80211_Register
Feb 11 15:58:41 Volumio wpa_supplicant[8172]: nl80211: Ignore RTM_NEWLINK event for foreign ifindex 4
Feb 11 15:58:41 Volumio kernel: MAC[Ver=0x76502000]
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: loading firmware mt7610u.bin
Feb 11 15:58:41 Volumio kernel: usbcore: registered new interface driver mt7610u
Feb 11 15:58:41 Volumio systemd[1]: Starting Load/Save RF Kill Switch Status of rfkill1...
Feb 11 15:58:41 Volumio systemd[1]: Started Load/Save RF Kill Switch Status of rfkill1.
Feb 11 15:58:41 Volumio kernel: usb 1-1.2: firmware mt7610u.bin loaded
Feb 11 15:58:41 Volumio kernel: fw version:0.1.00
Feb 11 15:58:41 Volumio kernel: build:7640
Feb 11 15:58:41 Volumio kernel: build time:
Feb 11 15:58:41 Volumio kernel: ilm length = 68780(bytes)
Feb 11 15:58:41 Volumio kernel: dlm length = 11476(bytes)
Feb 11 15:58:41 Volumio kernel: #
Feb 11 15:58:41 Volumio kernel: loading fw
Feb 11 15:58:41 Volumio kernel: pos = 0
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 2040
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 4080
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 6120
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 8160
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 10200
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 12240
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 14280
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 16320
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 18360
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 20400
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 22440
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 24480
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 26520
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 28560
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 30600
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 32640
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 34680
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 36720
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 38760
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 40800
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 42840
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 44880
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 46920
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 48960
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 51000
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 53040
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 55080
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 57120
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 59160
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 61200
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 63240
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 65280
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 67320
Feb 11 15:58:41 Volumio kernel: sent_len = 1396
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 0
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 2040
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 4080
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 6120
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 8160
Feb 11 15:58:41 Volumio kernel: sent_len = 2040
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel: pos = 10200
Feb 11 15:58:41 Volumio kernel: sent_len = 1276
Feb 11 15:58:41 Volumio kernel: .
Feb 11 15:58:41 Volumio kernel:
Feb 11 15:58:41 Volumio kernel: #
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c1028d9c!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c1028de0!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c1028e24!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c1028d58!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c1028c8c!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c1028cd0!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c0fbca64!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c0fabeac!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c0fabef4!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c0fbcb40!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c0fbc9dc!
Feb 11 15:58:41 Volumio kernel: RTMP_TimerListAdd: add timer obj c0fbcafc!
Feb 11 15:58:41 Volumio kernel: cfg_mode=13
Feb 11 15:58:41 Volumio kernel: wmode_band_equal(): Band Not Equal!
Feb 11 15:58:41 Volumio kernel: 1. Phy Mode = 61
Feb 11 15:58:41 Volumio kernel: 2. Phy Mode = 61
Feb 11 15:58:41 Volumio kernel: /home/pi/wifi-src/mt7610u/chips/mt76x0.c:1703 assert (pAd->TxPower[choffset].Channel == 36)failed
Feb 11 15:58:41 Volumio kernel: ERROR!!!
Feb 11 15:58:41 Volumio kernel: E2PROM: WRONG VERSION 0x2, should be 1
Feb 11 15:58:41 Volumio kernel: BT Coexistence word [66] = 0000ffff
Feb 11 15:58:41 Volumio kernel: 0x24 = 0xffef, 0x0104 = 0x0033ffef
Feb 11 15:58:41 Volumio kernel: EEPROM_NIC_CFG1_OFFSET = 0xfd11
Feb 11 15:58:41 Volumio kernel: mt76x0_read_tx_alc_info_from_eeprom: EEPROM_MT76x0_TEMPERATURE_OFFSET (0xD1) = 0xf8
Feb 11 15:58:41 Volumio kernel: mt76x0_read_tx_alc_info_from_eeprom: TemperatureOffset = 0xfffffff8
Feb 11 15:58:41 Volumio kernel: Temperature Tx ALC not enabled
Feb 11 15:58:41 Volumio kernel: 3. Phy Mode = 61
Feb 11 15:58:41 Volumio kernel: TxPath = 1, RxPath = 1, RFIC=17
Feb 11 15:58:41 Volumio kernel: RTMPSetPhyMode: channel is out of range, use first channel=1
Feb 11 15:58:41 Volumio kernel: MCS Set = ff 00 00 00 01
Feb 11 15:58:41 Volumio wpa_supplicant[8172]: nl80211: Ignore RTM_NEWLINK event for foreign ifindex 4
Feb 11 15:58:41 Volumio kernel: <==== rt28xx_init, Status=0
Feb 11 15:58:41 Volumio kernel: 80211> re-init bands...
Feb 11 15:58:41 Volumio kernel: 80211> re-init bands...
Feb 11 15:58:41 Volumio kernel: 80211> RFICType = 3
Feb 11 15:58:41 Volumio kernel: 80211> Number of channel = 44
Feb 11 15:58:41 Volumio kernel: 80211> Number of rate = 12
Feb 11 15:58:41 Volumio kernel: 80211> CurTxPower = 0 dBm
Feb 11 15:58:41 Volumio kernel: 80211> TxStream = 1
Feb 11 15:58:41 Volumio kernel: crda> CFG80211_RegRuleApply ==>
Feb 11 15:58:41 Volumio kernel: crda> reset chan/power for 2.4GHz
packet_write_wait: Connection to 192.168.178.29 port 22: Broken pipe

**Comment by macmpi** [comment] 2018-02-11 17:30
ok...bad. :(
Seems like [MrEngman has changed it's repo structure recently!...](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371&p=1271918#p1271918)
I'll adapt the build script accordingly: hopefully this should fix it next time

**Comment by macmpi** [comment] 2018-02-11 21:09
@thomasdoerr 
While you have internet access (do not run install-wifi script), can you try the following from a newly imaged 2.361 SD:
```
mkdir wifi
cd wifi
wget http://downloads.fars-robotics.net/wifi-drivers/mt7610-drivers/mt7610-4.9.65-v7-1056.tar.gz 
tar xf mt7610-4.9.65-v7-1056.tar.gz
sed -i 's/^kernel=.*$/kernel=4.9.65-v7+/' install.sh
sudo sh install.sh
rm -rf *
```
then reboot & check if dongle works then.

**Comment by macmpi** [comment] 2018-02-12 09:15
@thomasdoerr 
Seems like @volumio just released 2.362 which should have MrEngman drivers fixed.
Thanks for feedback on such new image.

**Comment by thomasdoerr** [comment] 2018-02-12 14:02
Hi, I upgraded my existing volumio version from 2.361 to 2.362 -> same issue
Fresh install of 2.362 -> same issue too.

Then I installed a fresh volumio version 2.246, because I was unsure, if TP-LINK or even my pi is still working correct....but it works fine with 2.246. TP-LINK connected to my router with 5 GHz.
I updated this version to the newest (2.362) and it again freezes :-( no luck

**Comment by macmpi** [comment] 2018-02-12 14:23
hum...this is very frustrating indeed.
What if on this failing 2.362 you `md5sum` (and note each hash) for the following files:
```
/lib/modules/4.9.65-v7+/kernel/drivers/net/wireless/mt7610u.ko
/etc/Wireless/RT2870STA/RT2870STA.dat
/lib/firmware/mt7610u.bin
/lib/firmware/mt7650u.bin
```
Then, after, do this while you are on ethernet:
```
mkdir wifi
cd wifi
wget http://downloads.fars-robotics.net/wifi-drivers/mt7610-drivers/mt7610-4.9.65-v7-1056.tar.gz 
tar xf mt7610-4.9.65-v7-1056.tar.gz
sed -i 's/^kernel=.*$/kernel=4.9.65-v7+/' install.sh
sudo sh install.sh
rm -rf *
```
(let know if script spits errors) and then `md5sum` the same previous files after install, then reboot and check dongle works.

If it still does not work, then do while you are hooked over ethernet
```
sudo wget http://downloads.fars-robotics.net/wifi-drivers/install-wifi -O /usr/bin/install-wifi
sudo chmod +x /usr/bin/install-wifi
sudo install-wifi
``` 
note script output, and again `md5sum` the same files after install, then reboot and check dongle works?

Sorry for all these tests, and thanks!

**Comment by macmpi** [comment] 2018-02-12 17:34
Thanks!
Ok, so at least now, original image and manual install contain the same files: nice.
But it still does not work :( ...

There was a time in previous trials where your managed to run `install-wifi` on broken system just fine. Curious why you can not anymore.
Do you have internal wifi disabled? Can you eventually re-enable it then?

**Comment by macmpi** [comment] 2018-02-13 07:15
in fact you may:
`sudo rm /lib/modules/4.9.65-v7+/kernel/drivers/net/wireless/mt7610u.ko`
then reboot, while having ethernet connected.
Then connect USB dongle: it should likely not crash, and you could pull & run `install-wifi` as previously.
Then to the md5sum again, reboot, and check if it then work.
If it crashes again, then the issue will be confirmed to be a driver bug...

**Comment by thomasdoerr** [comment] 2018-02-14 06:08
I can try that over the weekend, I’ll keep you posted

**Comment by thomasdoerr** [comment] 2018-02-18 11:08
after removing the driver, I can plug TP-LINK and a reboot.
I can then install the driver, but after a reboot it hangs again.
md5sums are the same as before. I can install a RASPBIAN and check that.

**Comment by macmpi** [comment] 2018-02-18 13:28
> md5sums are the same as before

Thanks for your confirmation indeed: I think your tests greatly help nailing-down the problem.

I suspect something went wrong in this driver build somewhere between kernel 4.9.36 (working) and 4.9.65 (failing).
Current Raspbian is 4.9.59, so somewhere in-between: would be interesting to know if issue shows-up there, and report accordingly to MrEngman in [his reference thread](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371&start=1300).

**Comment by macmpi** [comment] 2018-03-05 10:03
@thomasdoerr did you have a chance to test on Raspian with `install-wifi` script?
Did the driver work then? (and confirm kernel version with `uname -a`)
Thanks.

**Comment by thomasdoerr** [comment] 2018-03-05 19:25
@macmpi sorry for the delay!

uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

I installed: http://downloads.fars-robotics.net/wifi-drivers/mt7610-drivers/mt7610-4.9.59-v7-1047.tar.gz 
and it works. 

c0ba761f712274332bfea9390207a808  /lib/modules/4.9.59-v7+/kernel/drivers/net/wireless/mt7610u.ko
60c46cc18503cc8be985e009be6d4cd3  /etc/Wireless/RT2870STA/RT2870STA.dat
9a047587617c9c8732b9c546fb4a0152  /lib/firmware/mt7610u.bin
8d8bc79bcad582d62996b1965f17af1a  /lib/firmware/mt7650u.bin

**Comment by macmpi** [comment] 2018-03-06 09:51
Thanks @thomasdoerr.
Raised question to MrEngman [here](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371&p=1281723#p1281752): feel free to follow-up there.

You may want to test interim Volumio2 v2.372 release (set Volumio in Test mode), which might bump kernel to 4.9.80 and related drivers... (make sure you start from a clean image, or erase all user data from it, if you manually installed driver on original image).
